# Generated by Django 4.2.2 on 2023-09-03 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_post_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_blog',
            name='pub_data',
            field=models.TimeField(default=datetime.datetime(2023, 9, 3, 8, 29, 20, 282014, tzinfo=datetime.timezone.utc)),
        ),
    ]
