# Generated by Django 4.2.2 on 2023-09-03 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_post_blog_pub_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_blog',
            name='pub_data',
            field=models.TimeField(default=datetime.datetime(2023, 9, 3, 8, 57, 32, 34336, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post_blog',
            name='title',
            field=models.CharField(max_length=70, unique_for_date='pub_date'),
        ),
    ]
